# Configurazione di build per Netlify
[build]
  command = "npm run build"
  publish = "dist"

# Configurazione per le variabili d'ambiente
[build.environment]
  NODE_VERSION = "18"

# Configurazione per il routing SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurazione per la cache dei file statici
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"